update scripts

diff --git a/lab_tasks/scripts/diskspace b/lab_tasks/scripts/diskspace
--- a/lab_tasks/scripts/diskspace
+++ b/lab_tasks/scripts/diskspace
@@ -2,4 +2,10 @@
 # Print available disk space for all the disks present in the diskspace.conf file
 # Contributed by: TA Sayan Ghosh
 
-xargs -I {} lsblk -rno FSAVAIL /dev/{} < "$HOME/.config/diskspace.conf" | paste -s -d " "
+CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/diskspace.conf"
+if [[ -r "$CONFIG_FILE" ]]; then
+  xargs -I {} lsblk -rno FSAVAIL /dev/{} < "$CONFIG_FILE" | paste -s -d " "
+else
+  echo "Error: Configuration file ($CONFIG_FILE) not found or not readable" >&2
+  exit 1
+fi
diff --git a/lab_tasks/scripts/dwnld_files_frm_urls b/lab_tasks/scripts/dwnld_files_frm_urls
--- a/lab_tasks/scripts/dwnld_files_frm_urls
+++ b/lab_tasks/scripts/dwnld_files_frm_urls
@@ -3,11 +3,19 @@
 # Download files from urls mentioned in a file
 # Contributed by: Bathula Sharath Kumar
 #
-read -rp "Enter the filename containing URLs: " url_file
+
+if [[ $# -ge 1 ]]; then
+  url_file="$1"
+else
+  read -rp "Enter the filename containing URLs: " url_file
+fi
+if [[ ! -r "$url_file" ]]; then
+  echo "Error: File not found or not readable!"
+  exit 1
+fi
 while read -r url; do
-	filename=$(basename "$url")
-	curl -o "$filename" "$url"
-	echo "Completed Download $filename"
+	wget "$url" --quiet &
 done < "$url_file"
+wait
 echo "--------------------------"
 echo "All files downloaded successfully!"
diff --git a/lab_tasks/scripts/faster b/lab_tasks/scripts/faster
--- a/lab_tasks/scripts/faster
+++ b/lab_tasks/scripts/faster
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# Speed up or slow down a video
 # usage faster <src video> <dest video> <speedup>
 
 # speedup is a floating point number, e.g. 2.0 for double speed
@@ -7,6 +8,21 @@
 
 if [ $# -ne 3 ]; then
     echo "Usage: $0 <src video> <dest video> <speedup>"
+    exit 1
+fi
+
+if [[ ! -r "$1" ]]; then
+    echo "Error: $1 is not a readable file"
+    exit 1
+fi
+
+if [[ -e "$2" ]]; then
+    echo "Error: $2 is an existing file"
+    exit 1
+fi
+
+if [[ ! "$3" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
+    echo "Error: $3 is not a floating point number"
     exit 1
 fi
 
